# language setting
language: node_js

# Mongo binds to 127.0.0.1 by default
services:
  - mongodb

# version numbers, testing against major versions of node
node_js:
  - "6"

# The path for Xunit to output test reports
env:
  - XUNIT_FILE=shippable/testresults/result.xml

# Create directories for test and coverage reports
before_script:
  - npm install -g grunt-cli
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

# for public modules use
git:
 submodules: false

# Running npm test to run your test cases
script:
 - npm test

# Tell istanbul to generate a coverage report
after_script:
  - mongo test --eval "db.dropDatabase()"
  - ./node_modules/.bin/istanbul cover grunt -- -u tdd
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
