version: 2

workflows:
  version: 2
  test-publish:
    jobs:
      - test-node6:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test-node8:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test-node-latest:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish:
          requires:
            - test-node6
            - test-node8
            - test-node-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

defaults: &defaults
  working_directory: ~/opentmi
  docker:
  - image: circleci/node:6.11.4
  steps:
    - checkout
    - run: node --version > _tmp_file
    - restore_cache:
        key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
    - run:
        name: install mongodb-org-tools
        command: |
          sudo npm install -g mongodb-prebuilt
    - run:
        name: versions
        command: |
          mongorestore --version
          node --version
          npm --version
          echo $NPM_CI_INSTALL
    - run:
        name: npm-install
        command: |
          npm $NPM_CI_INSTALL
          sudo npm install -g grunt-cli

    - save_cache:
        key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: test-node
        command: npm test
        environment:
          REPORTER: mocha-circleci-reporter
          MOCHA_FILE: junit/test-results.xml
    - run:
        name: coveralls
        command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - run:
        name: test-api
        command: |
          MOCHA_FILE=junit/apitests.xml grunt apitests --silent
          MOCHA_FILE=junit/clustertests.xml grunt clustertests --silent
    - run:
        name: lint
        command: npm run lint
        when: always
    - store_test_results:
        path: junit
    - store_artifacts:
        path: junit
    - store_artifacts:
        path: db.log
        prefix: mongolog
    - store_artifacts:
        path: docs
        prefix: documentations
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: coverage/coverage.json
jobs:
  test-node6:
    <<: *defaults
    docker:
    - image: circleci/node:6.14.4-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
       NODE_ENV: test
       NPM_CI_INSTALL: "install"
    - image: mongo:4.1.2
  test-node8:
    <<: *defaults
    docker:
    - image: circleci/node:8.12.0-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
       NODE_ENV: test
       NPM_CI_INSTALL: "install"
    - image: mongo:4.1.2
  test-node-latest:
    <<: *defaults
    docker:
    - image: circleci/node:latest-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
       NODE_ENV: test
       NPM_CI_INSTALL: "install"
    - image: mongo:4.1.2
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: node --version > _tmp_file
      - restore_cache:
          key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: echo npm publish




#version: 2
#jobs:
#  build:
#    working_directory: ~/opentmi
#    docker:
#      - image: circleci/node:8.11.4-browsers
#        environment:
#          CHROME_BIN: "/usr/bin/google-chrome"
#          NODE_ENV: test
#          XUNIT_FILE: shippable/testresults/result.xml
#      - image: mongo:4.1.2
#    steps:
#      - checkout
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#      - run:
#          name: install mongodb-org-tools
#          command: |
#            sudo npm install -g mongodb-prebuilt
#      - run:
#          name: versions
#          command: |
#            mongorestore --version
#            node --version
#            npm --version
#      - run:
#          name: prepare
#          command: |
#            sudo npm install -g grunt-cli
#            mkdir -p shippable/testresults
#            mkdir -p shippable/codecoverage
#            mkdir junit
#      - run:
#          name: install-npm
#          command: npm install
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
#      - run:
#          name: test
#          command: |
#            MOCHA_FILE=junit/apitests.xml grunt apitests --silent
#            MOCHA_FILE=junit/clustertests.xml grunt clustertests --silent
#            npm run test
#      - run:
#          name: coveralls
#          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#      - run:
#          name: lint
#          command: npm run lint
#          when: always
#      - store_test_results:
#          path: junit
#      - store_test_results:
#          path: coverage/coverage.json
#      - store_artifacts:
#          path: junit
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_artifacts:
#          path: shippable/testresults
#          prefix: testresults
#      - store_artifacts:
#          path: db.log
#          prefix: mongolog
#      - store_artifacts:
#          path: log
#          prefix: logs
