name: Dockerimage

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
     paths-ignore:
      - '**/*.md'
  release:
env:
  IMAGE_NAME: opentmi

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      
      - name: build
        run: docker build . -t image
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.event.pull_request.title }}
      
      - name: resolve tag
        id: vars
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          
          
          # Use Docker `<branch>` tag convention
          [ "$VERSION" == "merge" ] && VERSION=${{ github.head_ref }}
          
          echo ::set-output name=docker_tag::${VERSION}
          echo tag=${VERSION}          
          
      
      - run: docker image ls
      
      - name: push
        run: |
          VERSION=${{ steps.vars.outputs.docker_tag }}
          
          # create image id for ghcr
          IMAGE_ID=opentmi/$IMAGE_NAME          
          echo IMAGE_ID=$IMAGE_ID, VERSION=$VERSION
          
          # tag image
          docker tag image ghcr.io/$IMAGE_ID:$VERSION
          
          # Removes the original image tag
          # Removes the original image tag
          docker rmi image
         
          echo Tags for $IMAGE_ID $(docker images ghcr.io/$IMAGE_ID --format="{{ .Tag }}")
          
          # Login to ghcr
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # push 
          docker push --all-tags ghcr.io/$IMAGE_ID
   
          # tag image
          docker tag image $IMAGE_ID:$VERSION
          
          # Login to Dockerhub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          # push 
          docker push --all-tags $IMAGE_ID
          
          docker rmi image


      
