name: Dockerimage

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
     paths-ignore:
      - '**/*.md'
  release:

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - uses: elgohr/Publish-Docker-Github-Action@master
        with: 
          name: opentmi/opentmi
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tag_semver: true
          no_push: ${{ github.event_name == 'push' }}

      - run: docker image ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: publish to dockerhub
        # if: github.event_name == 'push' || github.event_name == 'tag'
        run:
          docker push -t opentmi

      
