name: Dockerimage

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
     paths-ignore:
      - '**/*.md'

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: opentmi
        image-tag: latest
